version: '3.8'

services:
  db:
    image: postgres:15
    container_name: parking-db
    restart: always
    environment:
      POSTGRES_USER: parking
      POSTGRES_PASSWORD: parking
      POSTGRES_DB: parking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
